language: erlang
otp_release:
  - 19.0
  - 18.3
  - 18.0
matrix:
  include:
    - otp_release: 19.0
      env:
        - BUILD_DOCS=true
        - DIALYZER=true
addons:
  apt:
    packages:
      - python-sphinx
      - enchant
before_script:
  - psql -c 'CREATE USER zotonic; ALTER USER zotonic CREATEDB;' -U postgres
install: echo "hi" # stub command; otherwise travis runs 'rebar get-deps'
script:
  - make all
  - make test
  - if [[ "$BUILD_DOCS" = true ]]; then make edocs; fi
  - if [[ "$BUILD_DOCS" = true ]]; then pip install --user -r doc/requirements.txt; fi
  - if [[ "$BUILD_DOCS" = true ]]; then make -C doc/ stubs; fi
  - if [[ "$BUILD_DOCS" = true ]]; then make -C doc/ SPHINXOPTS='-nW' html; fi
  - ./rebar3 xref
  - if [[ "$DIALYZER" = true ]]; then ./rebar3 dialyzer; fi
sudo: false
branches:
  only:
    - master
    - 0.x
notifications:
  email:
    # recipients:
    #   - zotonic-commits@googlegroups.com
    on_success: change #[always|never|change] # default: change
    on_failure: always #[always|never|change] # default: always
  irc:
    channels:
      - "chat.freenode.net#zotonic"
    on_success: change #[always|never|change] # default: change
    on_failure: always #[always|never|change] # default: always
    template:
      - "New commit on %{repository_name}/%{branch} by %{author}:  %{message} (%{commit}) "
      - "Build details: %{build_url}"
